"""
NEXUS: Zero Day — In-Game Help System
A tabbed help window covering getting started, the interface,
mission walkthrough, command reference, and tips.
"""

import tkinter as tk
from tkinter import font as tkfont

C = {
    "bg":        "#080c0a",
    "bg2":       "#0d1410",
    "bg3":       "#111a16",
    "green":     "#00ff88",
    "green_dim": "#00aa55",
    "green_dk":  "#003322",
    "amber":     "#ffaa00",
    "red":       "#ff3344",
    "cyan":      "#00ccff",
    "purple":    "#cc44ff",
    "text":      "#c0e8d0",
    "text_dim":  "#4a7a5a",
    "border":    "#1a3328",
}

# ── Content for every tab ──────────────────────────────────────────────────

SECTIONS = {
    "GETTING STARTED": [
        ("WELCOME TO NEXUS", "cyan", None),
        ("", None, None),
        ("You are Alex Ryder — handle: gh0st. Former network engineer, now hacktivist.", None, None),
        ("Vera Kaine (0xVERA), ex-NSA operative, has recruited you to expose PROJECT LAZARUS —", None, None),
        ("a corporate internet kill-switch hidden inside global CDN infrastructure.", None, None),
        ("", None, None),
        ("Your first target is a low-security MediaBridge relay node. Prove you can", None, None),
        ("operate cleanly, and the real work begins.", None, None),
        ("", None, None),
        ("── STEP 1 — Accept a Contract ─────────────────────────────────────────", "green", None),
        ("", None, None),
        ("Three contracts are waiting in the RIGHT PANEL →", None, None),
        ("Click any mission card to accept it, or type in the terminal:", None, None),
        ("", None, None),
        ("    missions", "green", None),
        ("    accept 1", "green", None),
        ("", None, None),
        ("── STEP 2 — Scan Your Target ──────────────────────────────────────────", "green", None),
        ("", None, None),
        ("Always recon before you attack. A port scan reveals open services and", None, None),
        ("version numbers that map directly to known vulnerabilities.", None, None),
        ("", None, None),
        ("    scan          (or click PORT SCAN in the left toolkit)", "green", None),
        ("", None, None),
        ("── STEP 3 — Run the Minigame ──────────────────────────────────────────", "green", None),
        ("", None, None),
        ("Every exploit launches a minigame. Your performance gives a success bonus.", None, None),
        ("Complete it for the best odds, or click SKIP MINIGAME for base probability.", None, None),
        ("", None, None),
        ("── STEP 4 — Execute & Exfiltrate ──────────────────────────────────────", "green", None),
        ("", None, None),
        ("After the minigame, click EXECUTE EXPLOIT. If successful, you gain shell", None, None),
        ("access (whoami → root). Run the remaining mission steps — the mission panel", None, None),
        ("tracks your progress. Complete all steps to finish the contract.", None, None),
        ("", None, None),
        ("── STEP 5 — Manage Your Trace ─────────────────────────────────────────", "green", None),
        ("", None, None),
        ("Every action raises your TRACE %. Hit 100% and you are BUSTED.", None, None),
        ("    bounce       — activates proxy routing, cuts trace generation 70%", "amber", None),
        ("    LOG WIPE     — shreds logs on a compromised host, -20% trace", "amber", None),
        ("", None, None),
        ("── STEP 6 — Save Often ─────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("Progress is not automatic. Click SAVE in the top bar or type:  save", None, None),
    ],

    "THE INTERFACE": [
        ("INTERFACE OVERVIEW", "cyan", None),
        ("", None, None),
        ("The game window is divided into five areas:", None, None),
        ("", None, None),
        ("── LEFT PANEL ──────────────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("NETWORK MAP   Lists every target you have discovered.", None, None),
        ("              Click a target to select it — it highlights green.", None, None),
        ("              The TARGET INTEL panel updates to show its details.", None, None),
        ("", None, None),
        ("TOOLKIT       12 exploit buttons below the map.", None, None),
        ("              Clicking one runs that exploit against the selected target", None, None),
        ("              and launches the minigame.", None, None),
        ("", None, None),
        ("── CENTRE PANEL ────────────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("TERMINAL      Your primary interface. Type commands here.", None, None),
        ("              Full command list: type  help  in the terminal.", None, None),
        ("", None, None),
        ("TAB BAR       Switch the centre panel between views:", None, None),
        ("  TERMINAL    Live terminal and command input", None, None),
        ("  STORY       Current chapter narrative and progress", None, None),
        ("  INTEL       Full intelligence report on the active target", None, None),
        ("  FILES       File system of a compromised target (needs shell)", None, None),
        ("  LOGS        Full operation log for the session", None, None),
        ("", None, None),
        ("── RIGHT PANEL ─────────────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("ACTIVE CONTRACTS   Shows available and active missions.", None, None),
        ("                   Click a card to accept. Active mission glows green.", None, None),
        ("", None, None),
        ("TARGET INTEL       IP, OS, ports, security level, and known", None, None),
        ("                   vulnerabilities for the currently selected target.", None, None),
        ("                   Shows ROOT ACCESS badge when you own a shell.", None, None),
        ("", None, None),
        ("── TOP BAR ─────────────────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("TIME       How long you have been playing this session", None, None),
        ("CREDITS    In-game currency earned from missions", None, None),
        ("REP        Reputation — increases with missions and Codex entries", None, None),
        ("SHELLS     Number of targets where you have root access", None, None),
        ("TRACE      Risk meter — keep this below 50%. Red at 70%, BUST at 100%.", None, None),
        ("", None, None),
        ("Buttons:   SAVE · LOAD · CODEX · HELP · F11 (fullscreen) · QUIT", None, None),
        ("", None, None),
        ("── KEYBOARD SHORTCUTS ──────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("F11          Toggle fullscreen", None, None),
        ("Escape       Exit fullscreen", None, None),
        ("↑ / ↓        Scroll through terminal command history", None, None),
        ("Tab          Autocomplete a command", None, None),
        ("Enter        Execute current command", None, None),
    ],

    "MISSION WALKTHROUGH": [
        ("CHAPTER 1 OPENING MISSIONS  —  Complete Walkthrough", "cyan", None),
        ("", None, None),
        ("If you're stuck on the first few missions, this is the guide.", None, None),
        ("Each step explains WHAT to do and WHY it matters in real security work.", None, None),
        ("Vera trains operators the way real red teams train new analysts:", None, None),
        ("understand the technique, then execute it.", None, None),
        ("", None, None),
        ("=" * 75, "text_dim", None),
        ("MISSION 1  —  GHOST IN THE WIRE", "cyan", None),
        ("=" * 75, "text_dim", None),
        ("Target: MEDIABRIDGE-RELAY-01  [10.44.12.8]  Security: LOW", "text_dim", None),
        ("Objective: Reconnaissance and config exfiltration", "text_dim", None),
        ("Reward: +10 REP  •  Proxy Chain v1", "amber", None),
        ("", None, None),
        ("Vera: \"If you can't do the boring work cleanly,", "text_dim", None),
        ("you'll die on the exciting work.\"", "text_dim", None),
        ("", None, None),
        ("── STEP 1  Accept the contract ─────────────────────────────────────────", "green", None),
        ("WHAT:  Click the Ghost in the Wire card in the right contracts panel.", None, None),
        ("       Or type:  missions   then   accept 1", None, None),
        ("", None, None),
        ("WHY:   In a real engagement, you don't touch a system without authorisation.", "amber", None),
        ("       The contract panel is your scope-of-work document. Accepting binds you", "amber", None),
        ("       to the objective, sets the target, and begins logging the operation.", "amber", None),
        ("", None, None),
        ("── STEP 2  Port scan ───────────────────────────────────────────────────", "green", None),
        ("WHAT:  Type:  scan   or click PORT SCAN in the toolkit.", None, None),
        ("       Minigame: click all 5 OPEN ports before the timer runs out.", None, None),
        ("       Closed ports show RST. Open ports show SYN/ACK responses.", None, None),
        ("", None, None),
        ("WHY:   Reconnaissance is the FIRST step of every real operation.", "amber", None),
        ("       Vera's rule: 80% of the work is preparation, 20% is the actual hack.", "amber", None),
        ("       A port scan tells you what services the target is running,", "amber", None),
        ("       which versions they're on, and which are likely to be vulnerable.", "amber", None),
        ("       Every open port is a potential way in. The version banners on", "amber", None),
        ("       each port are matched against the CVE database to find weaknesses.", "amber", None),
        ("", None, None),
        ("       In the real world, port scanners like Nmap do exactly this.", None, None),
        ("       Skipping this step is how junior pentesters get caught — they", None, None),
        ("       attack a service that isn't there, generate noise, and burn the op.", None, None),
        ("", None, None),
        ("── STEP 3  Review your intel ───────────────────────────────────────────", "green", None),
        ("WHAT:  Click the INTEL tab in the Target panel, or type:  intel", None, None),
        ("", None, None),
        ("       Key findings on this target:", None, None),
        ("       • Port 21 — Anonymous FTP enabled (no credentials needed)", None, None),
        ("       • Port 22 — OpenSSH 8.2p1 (Ubuntu 20.04, last patched late 2020)", None, None),
        ("       • Port 80 — nginx web server", None, None),
        ("       • Port 8080 — Apache Tomcat (outdated, has known CVEs)", None, None),
        ("", None, None),
        ("WHY:   The intel panel is where you DECIDE which weakness to exploit.", "amber", None),
        ("       Real attackers don't kick down the front door. They look for the", "amber", None),
        ("       window someone forgot to lock. On this target, that's anonymous FTP —", "amber", None),
        ("       a feature someone enabled for convenience and forgot to disable.", "amber", None),
        ("", None, None),
        ("── STEP 4  Connect to the target ───────────────────────────────────────", "green", None),
        ("WHAT:  Type:  connect 10.44.12.8", None, None),
        ("       Your prompt changes to  gh0st@10:~$  confirming the connection.", None, None),
        ("       Explore with:  whoami  •  ps  •  netstat  •  ls", None, None),
        ("", None, None),
        ("WHY:   Connecting puts you on the target machine but with no privileges.", "amber", None),
        ("       Think of it as walking into a building lobby — you're inside, but", "amber", None),
        ("       you can't open any of the office doors yet. The exploration commands", "amber", None),
        ("       let you map the environment from the inside, which often reveals", "amber", None),
        ("       things port scanning missed.", "amber", None),
        ("", None, None),
        ("── STEP 5  Gain shell access ───────────────────────────────────────────", "green", None),
        ("WHAT:  Click BRUTE FORCE in the toolkit (exploits the FTP weakness).", None, None),
        ("       Minigame: Cipher Decoder. Four rounds of Caesar-shifted words.", None, None),
        ("       Tip: A shift of +3 turns 'admin' into 'dgplq'. Work out the shift", None, None),
        ("       from one letter and apply it to the rest.", None, None),
        ("", None, None),
        ("       Success: prompt changes to  gh0st@10:~#   The # means ROOT.", None, None),
        ("       The ROOT ACCESS badge appears in the Target Intel panel.", None, None),
        ("", None, None),
        ("WHY:   This is privilege escalation — going from a low-level user to", "amber", None),
        ("       full system control. In real attacks this is often the hardest step.", "amber", None),
        ("       In this mission it's easy because the system is misconfigured.", "amber", None),
        ("       Real-world example: the Mirai botnet (2016) infected 600,000 devices", "amber", None),
        ("       using exactly this technique — default credentials no one changed.", "amber", None),
        ("", None, None),
        ("── STEP 6  Exfiltrate the config ───────────────────────────────────────", "green", None),
        ("WHAT:  Type:  exploit exfil", None, None),
        ("       Or click the EXFIL step in the active mission panel.", None, None),
        ("", None, None),
        ("WHY:   Exfiltration is the actual goal of the mission — extracting the", "amber", None),
        ("       data you came for, in this case the routing config that contains", "amber", None),
        ("       the LAZARUS-ROUTE-ALPHA tag. Everything before this was setup.", "amber", None),
        ("       Real attackers stage data carefully and exfiltrate slowly to avoid", "amber", None),
        ("       triggering volume-based alerts. Here ARIA handles the chunking.", "amber", None),
        ("", None, None),
        ("── MISSION COMPLETE ────────────────────────────────────────────────────", "cyan", None),
        ("Terminal prints the completion banner. Vera delivers the debrief.", None, None),
        ("ARIA offers to open the Codex for Port Scanning. ALWAYS READ IT — +2 REP", None, None),
        ("and the real-world context that makes the next missions easier.", None, None),
        ("", None, None),
        ("", None, None),
        ("=" * 75, "text_dim", None),
        ("MISSION 2  —  DEFAULT SINS", "cyan", None),
        ("=" * 75, "text_dim", None),
        ("Target: MEDIABRIDGE-CMS  [10.44.12.21]  Security: LOW", "text_dim", None),
        ("Objective: Compromise the CMS, plant a passive monitor", "text_dim", None),
        ("Reward: +14 REP  •  Credential Stuffer item", "amber", None),
        ("", None, None),
        ("Kai: \"admin / admin123. Fourteen seconds. I'm not joking.\"", "text_dim", None),
        ("", None, None),
        ("── STEP 1  Accept and scan ─────────────────────────────────────────────", "green", None),
        ("WHAT:  accept the mission, then  scan", None, None),
        ("       Same Port Mapper minigame as Mission 1. Open ports: 22, 80, 443, 3306.", None, None),
        ("", None, None),
        ("WHY:   Always scan a NEW target, even if you've scanned similar ones before.", "amber", None),
        ("       The CMS server is on the same subnet but runs different services.", "amber", None),
        ("       Port 3306 is MySQL — important context for later missions.", "amber", None),
        ("", None, None),
        ("── STEP 2  Connect and recon the web app ───────────────────────────────", "green", None),
        ("WHAT:  connect 10.44.12.21", None, None),
        ("       Click WEB RECON in the toolkit (or type:  exploit recon).", None, None),
        ("       This identifies the CMS software and its admin login URL.", None, None),
        ("", None, None),
        ("WHY:   Web reconnaissance is the OSINT equivalent of port scanning,", "amber", None),
        ("       but for web applications. You're looking for: login pages, exposed", "amber", None),
        ("       admin panels, API endpoints, error messages that leak software", "amber", None),
        ("       versions, robots.txt, and .git directories that shouldn't be public.", "amber", None),
        ("       This is what Burp Suite and OWASP ZAP do in real engagements.", "amber", None),
        ("", None, None),
        ("── STEP 3  Brute force the credentials ─────────────────────────────────", "green", None),
        ("WHAT:  Click BRUTE FORCE. Minigame: Cipher Decoder (4 rounds).", None, None),
        ("       The exploit tries a list of default credentials against the admin panel.", None, None),
        ("", None, None),
        ("WHY:   This is a credential stuffing attack — trying known username/password", "amber", None),
        ("       combinations from breach databases and default-credential lists.", "amber", None),
        ("       It works because:", "amber", None),
        ("       • Administrators leave default credentials enabled (admin/admin123)", "amber", None),
        ("       • Users reuse passwords across services", "amber", None),
        ("       • Older devices ship with the same password from the factory", "amber", None),
        ("", None, None),
        ("       The Mirai botnet (real-world) used exactly 62 default credentials", None, None),
        ("       to compromise 600,000 IoT devices in 2016. No sophistication required.", None, None),
        ("", None, None),
        ("── STEP 4  Plant the passive monitor ───────────────────────────────────", "green", None),
        ("WHAT:  exploit implant   (or click the IMPLANT step)", None, None),
        ("       Minigame: Firewall Bypass — match incoming packet patterns to", None, None),
        ("       allowed signatures fast enough that no alert fires.", None, None),
        ("", None, None),
        ("WHY:   A passive monitor records what passes through the system WITHOUT", "amber", None),
        ("       modifying anything. This is critical — if you change a file or alter", "amber", None),
        ("       a config, the next admin audit catches you and the whole operation", "amber", None),
        ("       burns. NEXUS prefers read-only access for as long as possible.", "amber", None),
        ("", None, None),
        ("       This is the difference between an APT (Advanced Persistent Threat)", None, None),
        ("       and a smash-and-grab. APTs sit quietly for months gathering intel.", None, None),
        ("       That's the play here.", None, None),
        ("", None, None),
        ("── STEP 5  Clean exit ──────────────────────────────────────────────────", "green", None),
        ("WHAT:  exploit clean_exit", None, None),
        ("       Or click the CLEAN EXIT step in the active mission panel.", None, None),
        ("", None, None),
        ("WHY:   The hardest part of any operation is leaving without trace.", "amber", None),
        ("       Clean exit wipes your session from logs, clears bash history,", "amber", None),
        ("       removes temporary files, and restores any modified timestamps.", "amber", None),
        ("       Skipping this step = the next admin notices a sudo session at", "amber", None),
        ("       3am from an IP nobody recognises = the implant gets removed = burned.", "amber", None),
        ("", None, None),
        ("", None, None),
        ("=" * 75, "text_dim", None),
        ("MISSION 3  —  INJECTION SEASON", "cyan", None),
        ("=" * 75, "text_dim", None),
        ("Target: MEDIABRIDGE-PORTAL  [10.44.12.55]  Security: LOW-MED", "text_dim", None),
        ("Objective: SQL injection to extract LAZARUS routing data", "text_dim", None),
        ("Reward: +18 REP  •  Custom SQLMap Payload", "amber", None),
        ("", None, None),
        ("Priya: \"They built the SQL query by concatenating user input.", "text_dim", None),
        ("Sit with that sentence for a moment.\"", "text_dim", None),
        ("", None, None),
        ("── STEP 1  Accept and recon ────────────────────────────────────────────", "green", None),
        ("WHAT:  Accept the mission. Type:  scan   then  connect 10.44.12.55", None, None),
        ("       This portal runs over HTTPS on port 443 with a login form.", None, None),
        ("", None, None),
        ("WHY:   Web portals are higher-value targets than relay nodes. They have", "amber", None),
        ("       direct database access and often expose customer records, internal", "amber", None),
        ("       data, and (in this case) routing metadata. Find the login form,", "amber", None),
        ("       find the database.", "amber", None),
        ("", None, None),
        ("── STEP 2  Test for SQL injection ──────────────────────────────────────", "green", None),
        ("WHAT:  Click SQL INJECT in the toolkit (or type:  exploit sqlinject).", None, None),
        ("       Minigame: Cipher Decoder, four rounds.", None, None),
        ("       The first round injects a test payload  ' OR 1=1 --", None, None),
        ("", None, None),
        ("WHY:   SQL injection happens when user input gets dropped directly into", "amber", None),
        ("       a database query. Example of the bug:", "amber", None),
        ("", None, None),
        ("       BAD:   query = \"SELECT * FROM users WHERE name='\" + input + \"'\"", "red", None),
        ("       GOOD:  query.execute(\"SELECT * FROM users WHERE name=?\", [input])", "green", None),
        ("", None, None),
        ("       The bad version lets you type   admin' OR 1=1 --   which makes the", "amber", None),
        ("       query always return true, bypassing the password check entirely.", "amber", None),
        ("       The fix — parameterised queries — is TWO LINES OF CODE. SQL injection", "amber", None),
        ("       has been on the OWASP Top Ten since 2003 and is still found regularly.", "amber", None),
        ("", None, None),
        ("── STEP 3  Enumerate the database schema ───────────────────────────────", "green", None),
        ("WHAT:  Once the injection succeeds, type:  exploit schema_dump", None, None),
        ("       Or click the SCHEMA step in the mission panel.", None, None),
        ("       This lists every table and column in the database.", None, None),
        ("", None, None),
        ("WHY:   Knowing the database structure is required before you can extract", "amber", None),
        ("       specific data. The interesting tables on this target:", "amber", None),
        ("       • routing_tables  — what you're after", "amber", None),
        ("       • users           — credentials for later use", "amber", None),
        ("       • audit_log       — note what's being recorded about your access", "amber", None),
        ("", None, None),
        ("── STEP 4  Extract the routing table ───────────────────────────────────", "green", None),
        ("WHAT:  exploit extract  (or click the EXTRACT step)", None, None),
        ("       Pulls the routing_tables data via the injection.", None, None),
        ("", None, None),
        ("WHY:   This is where the LAZARUS story actually starts. Inside 12 megabytes", "amber", None),
        ("       of routing data is a metadata field — internal_priority_class —", "amber", None),
        ("       with 47 records tagged LAZARUS-ROUTE-ALPHA. That tag isn't in any", "amber", None),
        ("       MediaBridge documentation. It's the first hard evidence of the", "amber", None),
        ("       shadow network you'll spend the next four chapters mapping.", "amber", None),
        ("", None, None),
        ("── STEP 5  Clean exit ──────────────────────────────────────────────────", "green", None),
        ("WHAT:  exploit clean_exit", None, None),
        ("", None, None),
        ("WHY:   SQL injection leaves traces — every malicious query is logged by", "amber", None),
        ("       the database engine. Clean exit scrubs the audit log entries that", "amber", None),
        ("       match your session and clears the web server access log.", "amber", None),
        ("", None, None),
        ("", None, None),
        ("=" * 75, "text_dim", None),
        ("GENERAL TIPS FOR EVERY MISSION", "cyan", None),
        ("=" * 75, "text_dim", None),
        ("", None, None),
        ("TRACE MANAGEMENT", "amber", None),
        ("Trace is your detection meter. Hits 100% = caught = mission failed.", None, None),
        ("• Type  bounce  EARLY to route through proxies (-70% trace on all actions)", None, None),
        ("• Click LOG WIPE between exploits to manually reduce trace by ~15%", None, None),
        ("• Failed exploits generate DOUBLE trace — succeed on the first attempt", None, None),
        ("", None, None),
        ("MINIGAME PERFORMANCE", "amber", None),
        ("Your minigame score directly boosts exploit success probability.", None, None),
        ("• Port Mapper: scan slowly and read each port carefully — accuracy > speed", None, None),
        ("• Cipher Decoder: work out the shift from one letter, apply to the rest", None, None),
        ("• Firewall Bypass: pattern-match on the first/last byte of each packet", None, None),
        ("", None, None),
        ("ALWAYS READ THE CODEX", "amber", None),
        ("After each mission ARIA offers the relevant Codex entry. Read it.", None, None),
        ("• +2 REP per topic (more with the Forensics 2 skill)", None, None),
        ("• Explains the real-world attack technique behind what you just did", None, None),
        ("• Includes a real breach case study (Mirai, Stuxnet, Equifax, SolarWinds...)", None, None),
        ("", None, None),
        ("SPEND REP EARLY", "amber", None),
        ("Click SKILLS in the top bar. The cheapest skills make the biggest difference.", None, None),
        ("Best opening unlock: STEALTH 1 (Quiet Footsteps) — 15 REP, -15% trace forever.", None, None),
        ("", None, None),
        ("IF YOU GET BUSTED", "amber", None),
        ("Not the end of the world. Load your last save (LOAD button in top bar).", None, None),
        ("Trace at 100% is a teaching moment — figure out which step generated the most", None, None),
        ("trace and bounce/wipe BEFORE doing it next time.", None, None),
        ("", None, None),
        ("── WHAT COMES NEXT ─────────────────────────────────────────────────────", "green", None),
        ("After all three Chapter 1 missions you unlock Chapter 2: The Network Beneath.", None, None),
        ("Chapter 2 introduces man-in-the-middle attacks, buffer overflows, and the", None, None),
        ("first network forensics mission. Difficulty steps up gradually.", None, None),
    ],

    "COMMANDS": [
        ("TERMINAL COMMAND REFERENCE", "cyan", None),
        ("", None, None),
        ("── NAVIGATION ──────────────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("help              Show this command list in the terminal", None, None),
        ("connect <ip>      Connect to a target by IP address", None, None),
        ("disconnect        Return to localhost", None, None),
        ("clear  /  cls     Clear the terminal output", None, None),
        ("history           Show your last 20 commands", None, None),
        ("", None, None),
        ("── RECONNAISSANCE ──────────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("scan  /  nmap     Port scan the current target", None, None),
        ("recon             OSINT reconnaissance — low trace, high info", None, None),
        ("intel             Switch to target intelligence tab", None, None),
        ("whoami            Current user on target (nobody / root)", None, None),
        ("ps                List running processes", None, None),
        ("netstat           Show active network connections", None, None),
        ("ls  /  dir        List files on the target (requires shell)", None, None),
        ("cat <file>        Read a file on the target (requires shell)", None, None),
        ("ifconfig          Show network interfaces and bounce status", None, None),
        ("", None, None),
        ("── MISSIONS ────────────────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("missions          List available contracts in the current chapter", None, None),
        ("accept <N>        Accept mission number N from the list", None, None),
        ("status            Full player stats — credits, rep, trace, shells", None, None),
        ("inventory         List items you have collected", None, None),
        ("credits           Show current credit balance", None, None),
        ("", None, None),
        ("── EXPLOITS ────────────────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("exploit <tool>    Run a named exploit, e.g:  exploit bruteforce", None, None),
        ("hack              Alias for bruteforce", None, None),
        ("recon             OSINT on current target", None, None),
        ("", None, None),
        ("  Available exploit names:", "text_dim", None),
        ("  portscan  •  bruteforce  •  sqlinject  •  overflow  •  sshcrack", "text_dim", None),
        ("  mitm  •  implant  •  lkm_compile  •  craft_phish  •  exfil", "text_dim", None),
        ("  zeroday_prep  •  ipc_corrupt  •  race_exploit  •  forge_cert", "text_dim", None),
        ("", None, None),
        ("── TRACE & STEALTH ─────────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("trace             Show trace level with contextual advice", None, None),
        ("bounce            Activate 3-hop proxy routing (trace gen -70%)", None, None),
        ("                  Also activates via the BOUNCE toolkit button", None, None),
        ("", None, None),
        ("  LOG WIPE button — shreds event logs on the target (-20% trace)", "amber", None),
        ("                    Requires active shell access first", "amber", None),
        ("", None, None),
        ("── VIEWS & INFORMATION ─────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("story             Switch to chapter narrative and progress view", None, None),
        ("logs              Switch to operation log view", None, None),
        ("intel             Switch to target intelligence view", None, None),
        ("codex             Open the cybersecurity knowledge base", None, None),
        ("", None, None),
        ("── GAME MANAGEMENT ─────────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("save              Open save menu (3 slots)", None, None),
        ("load              Open load menu", None, None),
        ("restart           Reset current run (after being BUSTED)", None, None),
    ],

    "TIPS & CODEX": [
        ("TIPS FOR EFFECTIVE OPERATIONS", "cyan", None),
        ("", None, None),
        ("── GENERAL ─────────────────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("Always scan before you attack. The intel tab shows exact vulnerability", None, None),
        ("names — these hint at which exploit to use.", None, None),
        ("", None, None),
        ("Activate BOUNCE early. It costs nothing and passively decays trace", None, None),
        ("over time while active. Run it at the start of every session.", None, None),
        ("", None, None),
        ("Higher minigame scores = higher exploit success rates. A perfect Port", None, None),
        ("Mapper run can push a 50% base chance up to near 80%.", None, None),
        ("", None, None),
        ("Failed exploits generate double trace. If a target feels too hard,", None, None),
        ("check your inventory — you may have an item that boosts that exploit.", None, None),
        ("", None, None),
        ("── TRACE MANAGEMENT ────────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("  0–30%    Safe. Operate normally.", "green", None),
        ("  30–60%   Elevated. Activate bounce if you haven't already.", "amber", None),
        ("  60–80%   Danger. Run LOG WIPE on any shell you own.", "amber", None),
        ("  80–99%   Critical. Stop exploiting. Wipe logs, wait for decay.", "red", None),
        ("  100%     BUSTED. Type  restart  to reset.", "red", None),
        ("", None, None),
        ("── THE CODEX ───────────────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("After each mission, ARIA offers to open the Codex for the technique", None, None),
        ("you just used. Reading it earns +2 REP and unlocks the entry.", None, None),
        ("", None, None),
        ("Open the Codex any time via the CODEX button in the top bar.", None, None),
        ("12 topics are available across the full game:", None, None),
        ("", None, None),
        ("  Ch1  Port Scanning & Reconnaissance", "text_dim", None),
        ("  Ch1  Default & Weak Credentials", "text_dim", None),
        ("  Ch1  SQL Injection", "text_dim", None),
        ("  Ch2  Man-in-the-Middle & TLS Security", "text_dim", None),
        ("  Ch2  Buffer Overflow Vulnerabilities", "text_dim", None),
        ("  Ch2  Phishing & Social Engineering", "text_dim", None),
        ("  Ch3  Rootkits & Persistence", "text_dim", None),
        ("  Ch3  Command & Control Infrastructure", "text_dim", None),
        ("  Ch3  Lateral Movement & Air Gap Attacks", "text_dim", None),
        ("  Ch4  Zero-Day Vulnerabilities", "text_dim", None),
        ("  Ch4  Race Conditions & Timing Attacks", "text_dim", None),
        ("  Ch4  PKI & Certificate Trust", "text_dim", None),
        ("  Ch3  Malware RE — Static Analysis", "text_dim", None),
        ("  Ch3  Malware RE — Dynamic Analysis", "text_dim", None),
        ("  Ch2  Network Forensics", "text_dim", None),
        ("  Ch5  Incident Response", "text_dim", None),
        ("  Ch5  Digital Forensics & Evidence", "text_dim", None),
        ("  Ch5  Operational Security (OPSEC)", "text_dim", None),
        ("", None, None),
        ("── THE STORY ───────────────────────────────────────────────────────────", "green", None),
        ("", None, None),
        ("Ch1  First Contact      — Learn to move. MediaBridge subsidiary.", None, None),
        ("Ch2  The Network Beneath — Follow the data. CDN infrastructure.", None, None),
        ("Ch3  Ghost Protocol     — OmniCorp knows you exist. Go deeper.", None, None),
        ("Ch4  Zero Day           — 72 hours to stop PROJECT LAZARUS.", None, None),
        ("Ch5  The Reckoning      — Voss comes back. NEXUS becomes the target.", None, None),
        ("", None, None),
        ("Type  story  in the terminal to read the current chapter narrative.", None, None),
        ("Character transmissions appear automatically as you complete missions.", None, None),
    ],

    "SKILL TREE": [
        ("OPERATOR PROGRESSION", "cyan", None),
        ("", None, None),
        ("Click the SKILLS button in the top bar to open the skill tree.", None, None),
        ("Spend REP on permanent upgrades organised across five branches:", None, None),
        ("", None, None),
        ("  RECON     — Intelligence gathering. +bonuses on scan and OSINT exploits.", None, None),
        ("  EXPLOIT   — Offensive operations. +bonuses on overflows, injections, zero-days.", None, None),
        ("  STEALTH   — Trace evasion. Lower trace generation, better bouncing, passive decay.", None, None),
        ("  FORENSICS — Defensive analysis. +bonuses on malware analysis and forensics work.", None, None),
        ("  RESOURCE  — Economy & meta. Credit grants, REP multipliers, minigame time bonuses.", None, None),
        ("", None, None),
        ("DESIGN", "amber", None),
        ("", None, None),
        ("  • Each branch has FOUR TIERS, unlocked sequentially. You must own Tier 1 to access Tier 2.", None, None),
        ("  • REP costs: 15  →  30  →  55  →  90 per tier.", None, None),
        ("  • Skills are PERMANENT — no respec needed, no penalty for waiting.", None, None),
        ("  • All effects stack additively. A focused build is powerful; a balanced one is flexible.", None, None),
        ("", None, None),
        ("STRATEGY", "amber", None),
        ("", None, None),
        ("  • Early game: STEALTH 1 (Quiet Footsteps) is the most cost-effective starting skill.", None, None),
        ("  • Mid game: focus one branch fully before diversifying. Tier 4 effects are substantial.", None, None),
        ("  • Late game: RESOURCE 4 (NEXUS Operator) accelerates everything else.", None, None),
        ("  • Failing exploits costs REP indirectly (lost rewards). STEALTH 3 reduces this risk.", None, None),
        ("", None, None),
        ("REP is earned from missions, reading Codex entries, and completing chapters.", None, None),
        ("There is enough REP across the full game to unlock approximately 75% of the tree.", None, None),
    ],
}


class HelpWindow:
    def __init__(self, parent):
        self.win = tk.Toplevel(parent)
        self.win.title("NEXUS — Help & Getting Started")
        self.win.configure(bg=C["bg"])
        self.win.geometry("860x640")
        self.win.transient(parent)
        self.win.resizable(True, True)
        self.win.minsize(700, 500)

        font_title = tkfont.Font(family="Courier New", size=13, weight="bold")
        font_tab   = tkfont.Font(family="Courier New", size=10, weight="bold")
        font_mono  = tkfont.Font(family="Courier New", size=10)
        font_small = tkfont.Font(family="Courier New", size=9)
        self.font_mono  = font_mono
        self.font_small = font_small

        # ── Header ──
        hdr = tk.Frame(self.win, bg=C["bg2"])
        hdr.pack(fill="x")
        tk.Label(hdr, text="◈ NEXUS: ZERO DAY — HELP & GETTING STARTED",
                 bg=C["bg2"], fg=C["green"], font=font_title, pady=8).pack(side="left", padx=12)
        tk.Button(hdr, text="✕ CLOSE", bg=C["bg3"], fg=C["text_dim"],
                  font=font_small, relief="flat", cursor="hand2",
                  activebackground=C["green_dk"], activeforeground=C["green"],
                  command=self.win.destroy).pack(side="right", padx=12, pady=6)

        tk.Frame(self.win, bg=C["border"], height=1).pack(fill="x")

        # ── Tab bar ──
        tab_bar = tk.Frame(self.win, bg=C["bg2"])
        tab_bar.pack(fill="x")
        self._tab_btns = {}
        self._active_tab = tk.StringVar(value="")

        for name in SECTIONS:
            btn = tk.Button(tab_bar, text=name, bg=C["bg2"], fg=C["text_dim"],
                            font=font_tab, relief="flat", bd=0, padx=14, pady=8,
                            cursor="hand2",
                            activebackground=C["green_dk"], activeforeground=C["green"],
                            command=lambda n=name: self._show_tab(n))
            btn.pack(side="left")
            self._tab_btns[name] = btn

        tk.Frame(self.win, bg=C["border"], height=1).pack(fill="x")

        # ── Content area ──
        content_frame = tk.Frame(self.win, bg=C["bg"])
        content_frame.pack(fill="both", expand=True)
        content_frame.grid_rowconfigure(0, weight=1)
        content_frame.grid_columnconfigure(0, weight=1)

        self._canvas = tk.Canvas(content_frame, bg=C["bg"], highlightthickness=0)
        sb = tk.Scrollbar(content_frame, orient="vertical", command=self._canvas.yview,
                          bg=C["bg"], troughcolor=C["bg2"], width=8)
        self._canvas.configure(yscrollcommand=sb.set)
        self._canvas.grid(row=0, column=0, sticky="nsew")
        sb.grid(row=0, column=1, sticky="ns")

        self._inner = tk.Frame(self._canvas, bg=C["bg"])
        self._cw = self._canvas.create_window((0, 0), window=self._inner, anchor="nw")

        self._inner.bind("<Configure>",
            lambda e: self._canvas.configure(scrollregion=self._canvas.bbox("all")))
        self._canvas.bind("<Configure>",
            lambda e: self._canvas.itemconfig(self._cw, width=e.width))
        self._canvas.bind("<MouseWheel>",
            lambda e: self._canvas.yview_scroll(int(-1*(e.delta/120)), "units"))
        self._canvas.bind("<Button-4>",
            lambda e: self._canvas.yview_scroll(-1, "units"))
        self._canvas.bind("<Button-5>",
            lambda e: self._canvas.yview_scroll(1, "units"))

        # Show first tab
        self._show_tab(list(SECTIONS.keys())[0])

    def _show_tab(self, name):
        # Update button highlight
        for n, btn in self._tab_btns.items():
            if n == name:
                btn.configure(bg=C["green_dk"], fg=C["green"])
            else:
                btn.configure(bg=C["bg2"], fg=C["text_dim"])

        # Clear content
        for w in self._inner.winfo_children():
            w.destroy()
        self._canvas.yview_moveto(0)

        # Render lines
        lines = SECTIONS[name]
        for text, color_key, _ in lines:
            if text == "":
                tk.Frame(self._inner, bg=C["bg"], height=6).pack(fill="x")
                continue

            fg = C.get(color_key, C["text"]) if color_key else C["text"]

            # Section dividers — lines starting with ──
            if text.startswith("──"):
                frame = tk.Frame(self._inner, bg=C["bg"])
                frame.pack(fill="x", padx=16, pady=(10, 2))
                tk.Label(frame, text=text, bg=C["bg"], fg=fg,
                         font=tkfont.Font(family="Courier New", size=10, weight="bold"),
                         anchor="w").pack(fill="x")
                tk.Frame(self._inner, bg=C["border"], height=1).pack(fill="x", padx=16, pady=(0, 4))
                continue

            # Command / mono lines (indented with spaces or all-caps short label)
            if text.startswith("    ") or (len(text) < 30 and text == text.upper() and text.strip()):
                font = self.font_mono
                pad_l = 32 if text.startswith("    ") else 16
            else:
                font = self.font_small
                pad_l = 16

            tk.Label(self._inner, text=text, bg=C["bg"], fg=fg,
                     font=font, anchor="w", justify="left",
                     wraplength=0).pack(fill="x", padx=(pad_l, 16), pady=1)
